baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Heybe.ai - AI Tools and Services for the Modern Web"

# Enable tags and categories for blog
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "A startup studio that develops AI tools and services for the modern web"
  images = ["img/og-image.jpg"]
  # Social media
  github = "https://github.com/heybe-ai"
  twitter = "https://x.com/heybeai"
  linkedin = "https://linkedin.com/company/heybe-ai"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5